mike/hide_about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("about/", views.AboutView.as_view(), name="about"),
    path("contacts/", views.ContactsView.as_view(), name="contacts"),
]

mike/main/urls.py
from django.urls import path

from . import views

app_name = "events"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
    path("about/", views.AboutView.as_view(), name="about"),
    path(
        "<slug:event_type>/",
        views.EventsView.as_view(),
        name="event_list_by_type",
    ),
    path(
        "<slug:event_type>/<int:pk>/",
        views.EventDetailView.as_view(),
        name="event_detail",
    ),
]

mike/mike/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("main.urls", namespace="main")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )

mike/main/models.py
from django.db import models


class Event(models.Model):
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=50, null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    date = models.DateField("date of event")
    description = models.TextField(null=True, blank=True)
    video_link = models.URLField(
        null=True,
        blank=True,
        help_text=(
            "If Youtube link like this: "
            "https://www.youtube.com/embed/kLiVzoNSDh4 "
            "if Vimeo: "
            "https://player.vimeo.com/video/819819044"
        ),
    )

    class TypeChoice(models.TextChoices):
        HIDDEN = "hidden", "HIDDEN"
        MEDIA_ARTIST = "media_artist", "MEDIA ARTIST"
        VIDEO_DESIGN = "video_design", "VIDEO DESIGN"
        AV_PERFORMANCE = "av_performance", "A/V PERFORMANCE"
        VISUALS = "visuals", "VISUALS"

    type = models.CharField(
        "type of event",
        max_length=15,
        choices=TypeChoice.choices,
        default=TypeChoice.HIDDEN,
    )

    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    pub_date = models.DateTimeField("date of add", auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"
        ordering = ["-date"]


class Image(models.Model):
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name="images",
    )
    image = models.ImageField(
        upload_to="images",
    )

    def __str__(self):
        return self.image.name

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"

mike/hide_about/views.py
from django.views.generic.base import TemplateView


class AboutView(TemplateView):
    """About."""

    template_name = "about/about.html"


class ContactsView(TemplateView):
    """Contacts."""

    template_name = "about/contacts.html"

mike/main/views.py
from django.views.generic import DetailView, ListView, TemplateView

from .models import Event


class AboutView(TemplateView):
    template_name = "main/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event_types"] = Event.TypeChoice.choices
        return context


class EventsView(ListView):
    template_name = "main/events.html"

    def get_queryset(self):
        return Event.objects.filter(type=self.kwargs["event_type"]).order_by("-date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event_types"] = Event.TypeChoice.choices
        return context


class EventDetailView(DetailView):
    model = Event
    template_name = "main/event_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["event_types"] = Event.TypeChoice.choices
        return context

mike/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    Default title :(
    {% endblock %}
  </title>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  <!-- Подключаем стилевой файл -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

  <body class="body" data-bs-theme="dark">
    <header class="mx-auto">
      {% include 'includes/header.html' %}
    </header>
    <main class="flex-fill">
      {% block content %}
      Контент не подвезли :(
      {% endblock %}
    </main>
    {% comment %} <footer class="mx-auto">
      {% include 'includes/footer.html' %}
    </footer> {% endcomment %}

    <!-- Optional JavaScript -->
    <!-- первых 2 не грузил jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"></script>

  </body>

</html>

mike/templates/includes/event.html
<div class="card border-0 bg-transparent">
	<div class="card-body p-0 pb-3">
		<a href="{% url 'main:event_detail' event.type event.id %}">
			<h3 class="card-title fs-3 text-white fw-light d-inline-block bg-dark p-3 m-0">{{ event.title }}</h3>
		</a>
	</div>
	<div class="row">
		<div class="col-md-8 ">
			<a href="{% url 'main:event_detail' event.type event.id %}">
				{% comment %} тут берём только первую картинку {% endcomment %}
				<img src="{{ event.images.first.image.url }}" class="card-img pb-3" alt="{{ event.images.first.image }}">

				{% comment %} далее перечисляем картинки {% endcomment %}
				{% comment %} {% for image in event.images.all %}
				<img src="{{ image.image.url }}" class="card-img" alt="{{ image.image }}">
				{% endfor %} {% endcomment %}
			</a>
		</div>
		<div class="col-md-4 p-0">
			<div class="card-body p-0 px-5">
				{% comment %} <h5 class="card-title">{{ event.title }}</h5> {% endcomment %}
				{%if event.subtitle%}
					<h6 class="card-subtitle fs-5 text-end text-muted mb-2">{{ event.subtitle }}</h6>
				{% endif %}
				<h6 class="card-subtitle fs-4 text-light fw-light text-end mb-2">{{ event.location }} {{ event.date|date:'Y' }}</h6>
				<p class="card-text fw-light text-end">{{ event.description }}</p>
			</div>
		</div>
	</div>
	{% comment %} {% if event.video_link %}
	<div class="video-container">
		<iframe id="ytplayer" type="text/html" width="720" height="405" src="{{ event.video_link }}" frameborder="0"
			allowfullscreen></iframe>
	</div>
	{% endif %} {% endcomment %}
</div>

mike/templates/includes/footer.html
<div class="d-flex justify-content-center py-4">

	<!-- E-mail icon with link -->
	<!-- default fill="currentColor"-->
	<a href="mailto:mi.ivanof@gmail.com">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-envelope mx-3"
			viewBox="0 0 16 16">
			<path
				d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
		</svg>
	</a>

	<!-- Instagram icon with link -->
	<!-- default fill="currentColor"-->
	<a href="https://www.instagram.com/iv.mike" target="_blank" rel="noopener">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-instagram mx-3"
			viewBox="0 0 16 16">
			<path
				d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
		</svg>
	</a>

	<!-- Twitter icon with link -->
	<!-- default fill="currentColor"-->
	<a href="https://twitter.com/Gusiatka" target="_blank" rel="noopener">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-twitter mx-3"
			viewBox="0 0 16 16">
			<path
				d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
		</svg>
	</a>

	<!-- Facebook icon with link -->
	<!-- default fill="currentColor"-->
	<!-- <a href="https://www.facebook.com/your-facebook-page" target="_blank" rel="noopener">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-facebook mx-3"
			viewBox="0 0 16 16">
			<path
				d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
		</svg>
	</a> -->

</div>

mike/templates/includes/header.html
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-expand-md navbar-dark bg-transparent">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'main:about' %}active{% endif %}" href="{% url 'main:about' %}">MIKE
            IV</a>
        </li>
        <li class="nav-item d-none d-md-block">
          <span class="nav-link">/</span>
        </li>
        {% for event_type, event_type_label in event_types %}
        {% if not event_type == 'hidden' %}
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.kwargs.event_type == event_type %}active{% endif %}"
            href="{% url 'main:event_list_by_type' event_type %}">{{ event_type_label }}</a>
        </li>
        {% if not forloop.last %}
        <li class="nav-item d-none d-md-block">
          <span class="nav-link">/</span>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
      </ul>
    </div>
  </div>
</nav>
{% endwith %}

mike/templates/main/event_detail.html
{% extends 'base.html' %}
{% block title %} Event detail {% endblock %}
{% block content %}
<div class="container-fluid">

	<div class="card my-3 border-0 bg-transparent">
		<div class="card-body p-0 mb-3">
			<h3 class="card-title d-inline-block fs-3 text-white fw-light bg-dark p-3 m-0">{{ object.title }}</h3>
		</div>
		{%if object.subtitle%}
			<h6 class="card-subtitle text-muted fs-5 mb-2">{{ object.subtitle }}</h6> {% endif %}
		<h6 class="card-subtitle fs-4 text-light fw-light mb-2">{{ object.location }} {{ object.date|date:'Y' }}</h6>  
		<p class="card-text fw-light text-justify">{{ object.description }}</p>
		<div class="">
			{% for image in object.images.all %}
			<img src="{{ image.image.url }}" class="card-img py-2" alt="{{ image.image }}">
			{% endfor %}
		</div>

		{% if object.video_link %}
		<div class="video-container">
			<iframe src="{{ object.video_link }}" class="py-2" allowfullscreen></iframe>
			{% comment %} <iframe id="ytplayer" type="text/html" width="720" height="405" src="{{ object.video_link }}" frameborder="0"
				allowfullscreen></iframe> {% endcomment %}
		</div>
		{% endif %}
		
	</div>

</div>
{% endblock %}

mike/templates/main/events.html
{% extends 'base.html' %}
{% block title %} SET DESIGN {% endblock %}
{% block content %}
<div class="container-fluid">
  {% for event in object_list %}
  {% include 'includes/event.html'%}
  {% endfor %}
</div>
{% endblock %}

mike/templates/main/index.html
{% extends "base.html" %} {% load static %} {% block title %}MEDIA ARTIST{% endblock %} {% block content %}
<div class="container-fluid py-3">
  {% comment %}
  <div class="d-flex justify-content-center">
    <h1 class="fs-2 fw-light">MIKE IV</h1>
  </div>
  {% endcomment %}
  <div class="row">
    <div class="col-md-4">
      <img
        src="{% static 'pics/mike_face.png' %}"
        class="img-fluid"
        alt="pics/mike_face.png"
      />
    </div>
    <div class="col-md-4">
      <p class="fw-light pt-2">
        <span class="fs-3 text-light">MIKE IV</span> is a media artist who
        specializes in creating visual effects using images, generative
        graphics, installations and audiovisual performances. His creative
        contributions are evident in numerous theatrical productions in which he
        participates as a member of the production team responsible for the
        video stage design. Collaborations with musicians, sound artists and
        performers from a variety of backgrounds allow him to convey the
        emotional impact of sound and movement through his video works,
        resulting in immersive audiovisual performances that shift the
        boundaries of audience perception.
      </p>
    </div>
    <div class="col-md-4">
      <img
        src="{% static 'pics/11.png' %}"
        class="img-fluid"
        alt="pics/11.png"
      />
    </div>
  </div>
  <!-- <p class="text-secondary">
    Mike IV is an artist in the field of media who specializes in creating visuals using images, generative graphics,
    installations, and audiovisual performances. His artistic contributions are showcased in theatre productions, where
    he is a member of the production team responsible for designing the video design of the stage. Collaborating with
    musicians and audio artists allows him to convey the emotional impact of sound through his graphic designs,
    resulting in the production of captivating audiovisual performances and music videos.
  </p> -->
</div>
<footer class="footer">{% include 'includes/footer.html' %}</footer>
{% endblock %}

mike/templates/main/interactive_cg.html
{% extends 'base.html' %}
{% block title %} INTERACTIVE CG {% endblock %}
{% block content %}
<div class="container-fluid">
  {% for event in object_list %}
  {% include 'includes/event.html'%}
  {% endfor %}
</div>
{% endblock %}

mike/templates/main/set_design.html
{% extends 'base.html' %}
{% block title %} SET DESIGN {% endblock %}
{% block content %}
<div class="container-fluid">
  {% for event in object_list %}
  {% include 'includes/event.html'%}
  {% endfor %}
</div>
{% endblock %}